import { NextResponse } from "next/server";
import clientPromise from "@/lib/mongodb";

// Run once to populate MongoDB with initial data.
// Call: GET /api/seed
// Remove or protect this route after seeding.

export async function GET() {
  const client = await clientPromise;
  const db = client.db();

  // ── Formations ─────────────────────────────────────────────────────────────
  const formations = [
    {
      id: "lancement-digital-30j",
      title: "Lancement Digital 30J",
      type: "Formation",
      coverGradient: "linear-gradient(135deg, #0D9488 0%, #0D1B5E 100%)",
      period: "30 jours",
      validityPeriod: "Accès à vie",
      price: "79€",
      members: 312,
      advantages: [
        "Méthode étape par étape pour ton premier produit digital",
        "Positionnement et choix de niche rentable",
        "Création d'une offre irrésistible",
        "Tunnel de vente simple et efficace",
        "Stratégie d'acquisition organique",
        "Templates et checklists inclus",
        "Accès à la communauté privée",
      ],
      modules: [
        { title: "Module 1 — Positionnement", lessons: ["Choisir ta niche rentable", "Définir ton avatar client", "Valider ton idée en 48h"] },
        { title: "Module 2 — L'Offre", lessons: ["Structurer une offre simple", "Fixer son prix", "Écrire sa page de vente"] },
        { title: "Module 3 — Le Tunnel", lessons: ["Page de capture", "Séquence email de bienvenue", "Page de vente + paiement"] },
        { title: "Module 4 — Acquisition", lessons: ["Stratégie de contenu organique", "Premiers 100 abonnés", "Convertir ses premiers clients"] },
      ],
      href: "/formations/lancement-digital-30j",
    },
    {
      id: "croissance-systeme",
      title: "Croissance Système",
      type: "Formation",
      coverGradient: "linear-gradient(135deg, #1A3FD8 0%, #0A1240 100%)",
      period: "6 semaines",
      validityPeriod: "Accès à vie",
      price: "149€",
      originalPrice: "199€",
      promo: "-25%",
      members: 187,
      advantages: [
        "Structurer un système d'acquisition reproductible",
        "Email automation et séquences de conversion",
        "Pages de vente haute conversion",
        "Pilotage par les KPI essentiels",
        "Offres ascendantes et upsell",
        "Suivi hebdomadaire des indicateurs",
        "Accès aux mises à jour à vie",
      ],
      modules: [
        { title: "Module 1 — KPI & Pilotage", lessons: ["Les métriques qui comptent vraiment", "Tableau de bord simple", "Prendre des décisions data-driven"] },
        { title: "Module 2 — Email Automation", lessons: ["Séquence de nurturing", "Emails de vente", "Segmentation et scoring"] },
        { title: "Module 3 — Pages de Conversion", lessons: ["Anatomie d'une page qui vend", "A/B testing rapide", "Optimiser son taux de conversion"] },
        { title: "Module 4 — Offres Ascendantes", lessons: ["Ladder de valeur", "Upsell et downsell", "Fidélisation et récurrence"] },
      ],
      href: "/formations/croissance-systeme",
    },
    {
      id: "content-machine",
      title: "Content Machine",
      type: "Masterclass",
      coverGradient: "linear-gradient(135deg, #B45309 0%, #1A3FD8 100%)",
      period: "1 journée intensive",
      validityPeriod: "Accès replay 12 mois",
      price: "49€",
      members: 524,
      advantages: [
        "Créer 30 jours de contenu en 3 heures",
        "Les formats qui convertissent sur chaque plateforme",
        "Calendrier éditorial clé en main",
        "Scripts vidéo et posts haute performance",
        "Replay intégral + slides disponibles",
      ],
      modules: [
        { title: "Partie 1 — Stratégie Contenu", lessons: ["Pourquoi la plupart échouent", "Les 3 piliers de contenu qui vendent", "Choisir ses plateformes"] },
        { title: "Partie 2 — Création en masse", lessons: ["La méthode batch", "Scripts et templates", "Outils pour aller 3x plus vite"] },
        { title: "Partie 3 — Calendrier & Systèmes", lessons: ["Calendrier éditorial 30 jours", "Automatiser la publication", "Analyser et itérer"] },
      ],
      href: "/formations/content-machine",
    },
    {
      id: "offre-premium",
      title: "Créer une Offre Premium",
      type: "Masterclass",
      coverGradient: "linear-gradient(135deg, #7C3AED 0%, #0D1B5E 100%)",
      period: "2h de masterclass",
      validityPeriod: "Accès replay à vie",
      price: "Gratuit",
      members: 891,
      advantages: [
        "Comprendre la psychologie de l'acheteur premium",
        "Structurer une offre à haute valeur perçue",
        "Pricing et positionnement haut de gamme",
        "Les erreurs qui font fuir les clients premium",
        "Q&A en direct enregistré",
      ],
      modules: [
        { title: "Partie 1 — Psychologie Premium", lessons: ["Ce que veut vraiment un acheteur premium", "Les signaux de confiance", "Positionnement haut de gamme"] },
        { title: "Partie 2 — Construire l'Offre", lessons: ["Valeur perçue vs valeur réelle", "Structurer les livrables", "Fixer un prix premium assumé"] },
        { title: "Partie 3 — Q&A Live", lessons: ["Questions des participants", "Études de cas commentées"] },
      ],
      href: "/formations/offre-premium",
    },
    {
      id: "mentorat-elite",
      title: "Mentorat Elite",
      type: "Accompagnement",
      coverGradient: "linear-gradient(135deg, #7C3AED 0%, #1A3FD8 100%)",
      period: "90 jours",
      validityPeriod: "Durée du programme",
      price: "390€",
      members: 43,
      advantages: [
        "Audit complet de ton business dès le départ",
        "Roadmap personnalisée sur 90 jours",
        "Sessions live hebdomadaires en groupe",
        "Accès direct pour questions par messagerie",
        "Revue mensuelle de tes indicateurs",
        "Accès à toutes les formations de la plateforme",
        "Certificat de fin de programme",
      ],
      modules: [
        { title: "Semaine 1-2 — Audit & Fondations", lessons: ["Audit complet de ton activité", "Identification des blocages", "Définition de la roadmap 90j"] },
        { title: "Semaine 3-6 — Acquisition", lessons: ["Optimisation de l'acquisition", "Tunnel et conversion", "Premiers paliers de revenus"] },
        { title: "Semaine 7-10 — Systèmes", lessons: ["Automatisation des process", "Délégation et outils", "Pilotage par les données"] },
        { title: "Semaine 11-13 — Scale", lessons: ["Stratégie de passage à l'échelle", "Offres premium", "Bilan et plan de continuation"] },
      ],
      href: "/formations/mentorat-elite",
    },
    {
      id: "acceleration-individuelle",
      title: "Accélération Individuelle",
      type: "Accompagnement",
      coverGradient: "linear-gradient(135deg, #C2410C 0%, #7C3AED 100%)",
      period: "30 jours intensif",
      validityPeriod: "Durée du programme",
      price: "290€",
      originalPrice: "390€",
      promo: "EARLY BIRD",
      members: 18,
      advantages: [
        "Suivi 1-to-1 avec Israël Oriadé",
        "2 appels stratégiques par semaine",
        "Plan d'action détaillé semaine par semaine",
        "Feedback sur tes créations (pages, offres, contenus)",
        "Accès prioritaire aux nouvelles ressources",
      ],
      modules: [
        { title: "Semaine 1 — Diagnostic & Plan", lessons: ["Appel de cadrage initial", "Analyse de ta situation", "Plan d'action semaine 1-4"] },
        { title: "Semaine 2-3 — Exécution rapide", lessons: ["Appels bi-hebdomadaires", "Feedback sur tes livrables", "Ajustements en temps réel"] },
        { title: "Semaine 4 — Bilan & Suite", lessons: ["Revue des résultats", "Identification des prochaines étapes", "Plan de continuation"] },
      ],
      href: "/formations/acceleration-individuelle",
    },
  ];

  // ── Ressources ──────────────────────────────────────────────────────────────
  const ressources = [
    {
      id: "ebook-positionnement",
      title: "Trouver ton positionnement rentable",
      desc: "Méthode simple pour sortir du flou et clarifier ton message en moins de 48h.",
      fullDesc: "Ce guide complet t'accompagne pas à pas pour sortir du flou et définir un positionnement clair, différenciant et rentable. Tu découvriras comment identifier ta niche, formuler ta proposition de valeur et te démarquer de la concurrence en moins de 48h.",
      category: "Ebook", type: "Gratuit", topic: "Business",
      author: "Israël Oriadé", rating: 4.8, downloads: 312,
      downloadHref: "#", detailHref: "#",
      gradient: "linear-gradient(135deg, #1A3FD8 0%, #6366F1 100%)",
      iconType: "book",
    },
    {
      id: "checklist-lancement",
      title: "Checklist lancement produit digital",
      desc: "Les 27 étapes indispensables avant de publier ton offre en ligne.",
      fullDesc: "Une checklist exhaustive qui couvre toutes les étapes critiques avant le lancement de ton produit digital : validation de l'offre, mise en place du tunnel, séquence email de lancement, et suivi post-publication. Aucune étape oubliée.",
      category: "Checklist", type: "Gratuit", topic: "Vente",
      author: "Israël Oriadé", rating: 4.9, downloads: 541,
      downloadHref: "#", detailHref: "#",
      gradient: "linear-gradient(135deg, #0D9488 0%, #22C55E 100%)",
      iconType: "check-circle",
    },
    {
      id: "template-tunnel",
      title: "Template tunnel de vente 7 étapes",
      desc: "Pages et séquences email prêtes à l'emploi pour convertir dès le premier jour.",
      fullDesc: "Un tunnel de vente complet en 7 étapes : page de capture, page de vente, upsell, downsell, confirmation et séquence email de suivi. Chaque élément est optimisé pour maximiser les conversions et peut être personnalisé en moins de 2 heures.",
      category: "Template", type: "Payant", topic: "Vente",
      author: "Israël Oriadé", rating: 4.7, downloads: 189, price: "19€",
      downloadHref: "#", detailHref: "#",
      gradient: "linear-gradient(135deg, #B45309 0%, #F5C200 100%)",
      iconType: "layout",
    },
    {
      id: "ebook-mindset",
      title: "Mindset de l'entrepreneur digital",
      desc: "Les 10 croyances qui bloquent les débutants — et comment les dépasser concrètement.",
      fullDesc: "Un ebook introspectif qui décortique les 10 blocages mentaux les plus courants chez les entrepreneurs débutants. Pour chaque croyance limitante, tu trouveras un exercice pratique pour la transformer en moteur de croissance.",
      category: "Ebook", type: "Gratuit", topic: "Développement personnel",
      author: "Israël Oriadé", rating: 4.6, downloads: 278,
      downloadHref: "#", detailHref: "#",
      gradient: "linear-gradient(135deg, #6B21E8 0%, #A78BFA 100%)",
      iconType: "bulb",
    },
    {
      id: "template-contenu",
      title: "Templates de contenu réseaux sociaux",
      desc: "30 templates Canva prêts à personnaliser pour Facebook, Instagram et LinkedIn.",
      fullDesc: "30 templates Canva professionnels couvrant les formats les plus engageants : carrousels, stories, posts statiques et visuels de témoignages. Chaque template est modifiable en quelques clics, sans compétence en design.",
      category: "Template", type: "Payant", topic: "Social Media",
      author: "Israël Oriadé", rating: 4.5, downloads: 143, price: "29€",
      downloadHref: "#", detailHref: "#",
      gradient: "linear-gradient(135deg, #C2410C 0%, #FB923C 100%)",
      iconType: "image",
    },
    {
      id: "checklist-ia",
      title: "Checklist outils IA pour ton business",
      desc: "Les 15 outils IA incontournables classés par usage — gratuits et payants.",
      fullDesc: "Une sélection rigoureuse des 15 meilleurs outils IA classés par catégorie : rédaction, création visuelle, automatisation, analyse de données et service client. Pour chaque outil, tu trouveras une note, le tarif et un cas d'usage concret.",
      category: "Checklist", type: "Gratuit", topic: "Tech",
      author: "Israël Oriadé", rating: 4.9, downloads: 407,
      downloadHref: "#", detailHref: "#",
      gradient: "linear-gradient(135deg, #1D4ED8 0%, #60A5FA 100%)",
      iconType: "sparkles",
    },
    {
      id: "guide-contenu-viral",
      title: "Guide contenu viral organique",
      desc: "Les formats et hooks qui génèrent de l'engagement sur chaque plateforme.",
      fullDesc: "Un guide stratégique sur les mécanismes du contenu viral : anatomie d'un hook, formats qui retiennent l'attention, fréquence de publication et recyclage intelligent du contenu. Applicable sur TikTok, Instagram Reels, LinkedIn et Facebook.",
      category: "Ebook", type: "Gratuit", topic: "Création de Contenu",
      author: "Israël Oriadé", rating: 4.7, downloads: 356,
      downloadHref: "#", detailHref: "#",
      gradient: "linear-gradient(135deg, #0E7490 0%, #22D3EE 100%)",
      iconType: "lightning",
    },
    {
      id: "template-strategie-marketing",
      title: "Template stratégie marketing 90 jours",
      desc: "Un plan d'action complet pour structurer ta croissance sur 3 mois.",
      fullDesc: "Un tableau de bord stratégique prêt à l'emploi pour planifier tes 90 prochains jours : objectifs SMART, canaux d'acquisition, calendrier éditorial, budget et KPIs à suivre semaine par semaine. Livré en Google Sheets et Notion.",
      category: "Template", type: "Payant", topic: "Marketing",
      author: "Israël Oriadé", rating: 4.8, downloads: 201, price: "24€",
      downloadHref: "#", detailHref: "#",
      gradient: "linear-gradient(135deg, #15803D 0%, #4ADE80 100%)",
      iconType: "chart",
    },
    {
      id: "guide-identite-visuelle",
      title: "Guide identité visuelle pour débutants",
      desc: "Couleurs, typographies et logotypes — crée une image de marque cohérente sans designer.",
      fullDesc: "Un guide pratique pour créer une identité visuelle professionnelle sans passer par un designer. Tu apprendras à choisir ta palette de couleurs, tes typographies, créer un logo simple et l'appliquer de façon cohérente sur tous tes supports.",
      category: "Ebook", type: "Gratuit", topic: "Design",
      author: "Israël Oriadé", rating: 4.6, downloads: 224,
      downloadHref: "#", detailHref: "#",
      gradient: "linear-gradient(135deg, #9D174D 0%, #F472B6 100%)",
      iconType: "brush",
    },
  ];

  // ── Outils ──────────────────────────────────────────────────────────────────
  const outils = [
    {
      slug: "notion",
      name: "Notion",
      category: "Productivité",
      rating: 5,
      tagline: "Centralise tes processus, contenus et suivi clients en un seul endroit.",
      logoGradient: "linear-gradient(135deg, #1A1A1A 0%, #3B3B3B 100%)",
      officialUrl: "https://www.notion.so",
      price: "Freemium — gratuit jusqu'à un usage solo, 8$/mois pour les équipes",
      features: [
        "Base de données relationnelles (tables, kanban, galerie, calendrier)",
        "Éditeur de pages tout-en-un (texte, code, embed, médias)",
        "Templates prêts à l'emploi pour tous les use cases",
        "API publique pour automatisations avancées",
        "Collaboration en temps réel",
        "Intégrations avec Zapier, Make, Slack et plus",
      ],
      pros: [
        "Extrêmement flexible — s'adapte à n'importe quel flux de travail",
        "Remplace facilement 3 à 4 outils (docs, CRM, project management, wiki)",
        "Interface épurée et agréable à utiliser au quotidien",
        "Version gratuite largement suffisante pour un solopreneur",
        "Communauté massive de templates partagés gratuitement",
      ],
      cons: [
        "Courbe d'apprentissage si tu veux exploiter toutes les fonctionnalités",
        "Peut devenir lent sur les très grandes bases de données",
        "Offline limité — nécessite une connexion pour la plupart des actions",
      ],
      tip: "Commence avec un template de CRM simple pour gérer tes prospects. Ajoute une vue Kanban pour suivre les étapes et une vue Tableau pour filtrer par statut. Tu auras un mini-CRM opérationnel en 30 minutes.",
      howToTry: "Va sur notion.so, crée un compte gratuit et duplique un template depuis la galerie officielle. Teste d'abord le template 'Personal CRM' ou 'Content Calendar' pour voir la puissance des bases de données.",
    },
    {
      slug: "convertkit",
      name: "ConvertKit",
      category: "Email Marketing",
      rating: 4,
      tagline: "Simple et fiable pour automatiser tes séquences email et gérer ta liste.",
      logoGradient: "linear-gradient(135deg, #FB6970 0%, #C2410C 100%)",
      officialUrl: "https://kit.com",
      price: "Gratuit jusqu'à 1 000 abonnés — 29$/mois au-delà",
      features: [
        "Séquences email automatisées avec logique conditionnelle",
        "Landing pages et formulaires d'opt-in intégrés",
        "Tags et segments pour personnaliser les envois",
        "Diffusion (broadcast) pour les newsletters",
        "Automatisations visuelles avec triggers multiples",
        "Commerce intégré pour vendre directement depuis l'outil",
      ],
      pros: [
        "Interface intuitive, prise en main en moins d'une heure",
        "Idéal pour les créateurs et solopreneurs",
        "Très bon taux de délivrabilité",
        "Plan gratuit généreux (jusqu'à 1 000 abonnés)",
        "Support réactif et documentation complète",
      ],
      cons: [
        "Moins de fonctionnalités avancées que ActiveCampaign ou Klaviyo",
        "L'éditeur d'emails est basique — peu de personnalisation visuelle",
        "Prix peut grimper vite avec une grande liste",
      ],
      tip: "Mets en place une séquence de bienvenue en 5 emails dès le premier abonné. Email 1 : accueil + promesse. Email 2 : ta meilleure ressource gratuite. Email 3 : ton histoire. Email 4 : ton offre phare. Email 5 : invitation à rejoindre ta communauté.",
      howToTry: "Crée un compte sur kit.com, connecte un formulaire à ta page de capture, et configure ta première séquence de bienvenue. Le plan gratuit suffit pour les 3 premiers mois.",
    },
    {
      slug: "canva",
      name: "Canva",
      category: "Design",
      rating: 5,
      tagline: "Crée des visuels professionnels sans designer en quelques minutes.",
      logoGradient: "linear-gradient(135deg, #00C4CC 0%, #7D2AE8 100%)",
      officialUrl: "https://www.canva.com",
      price: "Freemium — gratuit limité, Canva Pro à 13€/mois",
      features: [
        "Milliers de templates pour posts, présentations, ebooks, logos",
        "Éditeur drag-and-drop sans compétences requises",
        "Brand Kit pour centraliser couleurs, polices et logos",
        "Suppression d'arrière-plan en un clic (Pro)",
        "Export multi-formats (PNG, PDF, MP4, GIF)",
        "Collaboration en équipe et partage de dossiers",
      ],
      pros: [
        "Accessibilité totale — zéro compétence graphique requise",
        "Gain de temps massif sur la production de contenus visuels",
        "Résultats très propres même avec la version gratuite",
        "Application mobile performante",
        "Idéal pour maintenir une identité visuelle cohérente",
      ],
      cons: [
        "Les créations restent reconnaissables comme 'Canva' avec les templates populaires",
        "Limites créatives comparé à Figma ou Photoshop pour des designs très personnalisés",
        "Certaines fonctionnalités indispensables (Brand Kit, background remover) réservées au Pro",
      ],
      tip: "Crée un dossier 'Brand Kit' avec tes couleurs exactes, tes 2 polices et ton logo. Ensuite, duplique toujours le même template de base pour tes posts. Tu produiras 10 visuels cohérents en 20 minutes au lieu de 2 heures.",
      howToTry: "Inscris-toi gratuitement sur canva.com et cherche un template pour ton réseau social principal. Lance-toi sur un post, un carousel ou une couverture d'ebook pour tester la prise en main.",
    },
    {
      slug: "systeme-io",
      name: "Systeme.io",
      category: "Tunnel de Vente",
      rating: 4,
      tagline: "Crée ton tunnel complet, ton email marketing et tes formations au même endroit.",
      logoGradient: "linear-gradient(135deg, #1A3FD8 0%, #0D9488 100%)",
      officialUrl: "https://systeme.io",
      price: "Gratuit jusqu'à 2 000 contacts — plans payants à partir de 27€/mois",
      features: [
        "Constructeur de tunnels de vente drag-and-drop",
        "Email marketing avec séquences et broadcasts",
        "Hébergement de formations en ligne",
        "Programme d'affiliation intégré",
        "Blog et pages de vente",
        "Automatisations entre tous les modules",
      ],
      pros: [
        "Tout-en-un — remplace ClickFunnels + ConvertKit + Teachable",
        "Plan gratuit très généreux (le meilleur du marché)",
        "Interface en français disponible",
        "Support client rapide et communauté active",
        "Idéal pour débuter sans exploser le budget outils",
      ],
      cons: [
        "Moins de flexibilité de design que ClickFunnels ou Leadpages",
        "L'éditeur de pages peut être limité pour des designs très personnalisés",
        "Moins connu → moins de ressources communautaires comparé aux concurrents",
      ],
      tip: "Utilise Systeme.io pour construire ton premier tunnel en 3 pages : page de capture → page de remerciement avec upsell → email de livraison. C'est faisable en une après-midi avec un template de base.",
      howToTry: "Crée un compte gratuit sur systeme.io sans carte bleue. Utilise le template 'Squeeze Page' pour lancer une première page de capture et teste l'envoi d'un email de bienvenue automatique.",
    },
    {
      slug: "chatgpt",
      name: "ChatGPT",
      category: "Intelligence Artificielle",
      rating: 5,
      tagline: "Accélère ta production de contenu, tes recherches et tes automatisations.",
      logoGradient: "linear-gradient(135deg, #10A37F 0%, #0D1B5E 100%)",
      officialUrl: "https://chat.openai.com",
      price: "Gratuit (GPT-3.5) — ChatGPT Plus à 20$/mois (GPT-4o)",
      features: [
        "Rédaction et amélioration de contenus (posts, emails, pages de vente)",
        "Analyse et résumé de documents longs",
        "Génération d'idées et brainstorming structuré",
        "Création de prompts systèmes pour automatisations",
        "Navigation web en temps réel (Plus)",
        "Génération d'images avec DALL-E (Plus)",
      ],
      pros: [
        "Gain de temps massif sur la production de contenu",
        "Polyvalent — utilisable pour presque toutes les tâches textuelles",
        "S'améliore constamment avec les nouvelles versions",
        "GPT-4o disponible gratuitement avec limitations",
        "Intégration possible dans n'importe quel workflow via l'API",
      ],
      cons: [
        "Peut générer des informations inexactes (hallucinations) — toujours vérifier",
        "Réponses parfois trop génériques sans prompt précis",
        "Contexte limité sur les conversations très longues",
      ],
      tip: "Ne jamais envoyer un texte généré sans le relire et l'adapter à ta voix. Utilise ChatGPT pour créer un premier jet à 70%, puis personnalise les 30% restants avec ton expérience, tes anecdotes et ta tonalité.",
      howToTry: "Va sur chat.openai.com et teste ce prompt : 'Écris 5 idées de posts LinkedIn pour un entrepreneur digital qui aide les débutants à lancer leur premier produit. Ton style : direct, concret, sans jargon.' Adapte ensuite les résultats.",
    },
    {
      slug: "loom",
      name: "Loom",
      category: "Vidéo & Communication",
      rating: 4,
      tagline: "Enregistre et partage des vidéos asynchrones pour gagner du temps sur les explications.",
      logoGradient: "linear-gradient(135deg, #625DF5 0%, #C026D3 100%)",
      officialUrl: "https://www.loom.com",
      price: "Gratuit jusqu'à 25 vidéos — Starter à 12.5$/mois",
      features: [
        "Enregistrement écran + webcam simultané en un clic",
        "Lien de partage instantané sans upload manuel",
        "Commentaires et réactions sur la timeline",
        "Transcription automatique des vidéos",
        "Intégration Notion, Slack, Gmail, Jira",
        "Analytics (vues, engagement, durée de visionnage)",
      ],
      pros: [
        "Remplace 80% des réunions Zoom par une vidéo de 3 minutes",
        "Gain de temps massif pour onboarding clients et explications techniques",
        "Très facile à utiliser — enregistrement en 2 clics",
        "Excellent pour créer du contenu tutoriel rapidement",
        "Lien de partage universel, pas besoin de compte pour visionner",
      ],
      cons: [
        "Plan gratuit limité à 25 vidéos (mais suffisant pour tester)",
        "Qualité vidéo dépend de ta connexion internet",
        "Moins adapté pour les vidéos longues ou les formations complètes",
      ],
      tip: "Utilise Loom pour répondre aux questions fréquentes de tes clients une fois, puis envoie le lien à tout le monde. Une vidéo de 3 minutes vaut mieux qu'un email de 20 lignes — et tu ne l'enregistres qu'une fois.",
      howToTry: "Installe l'extension Chrome sur loom.com, crée un compte gratuit et enregistre ta première vidéo de présentation de 2 minutes. Partage le lien avec un client ou un prospect pour tester la réception.",
    },
  ];

  // ── Contenus ────────────────────────────────────────────────────────────────
  const contenus = [
    { id: "fb-1",  type: "post", platform: "Facebook",         description: "Tu veux lancer ton business digital mais tu ne sais pas par où commencer ? Voici la méthode en 3 étapes.", coverGradient: "linear-gradient(135deg, #1877F2 0%, #0D1B5E 100%)", postedAt: "2026-03-20", href: "https://facebook.com" },
    { id: "li-1",  type: "post", platform: "LinkedIn",         description: "J'ai analysé 200 offres digitales qui se vendent bien. Voici les 5 caractéristiques communes.", coverGradient: "linear-gradient(135deg, #0A66C2 0%, #0D1B5E 100%)", postedAt: "2026-03-21", href: "https://linkedin.com" },
    { id: "yt-1",  type: "post", platform: "YouTube",          description: "Comment créer un tunnel de vente qui convertit à froid — Étude de cas complète.", coverGradient: "linear-gradient(135deg, #FF0000 0%, #7C0000 100%)", postedAt: "2026-03-19", href: "https://youtube.com" },
    { id: "ac-1",  type: "post", platform: "Autres Créateurs", description: "Un article de Alex Hormozi sur la structure d'une offre irrésistible.", coverGradient: "linear-gradient(135deg, #7C3AED 0%, #0D1B5E 100%)", postedAt: "2026-03-22", href: "https://acquisition.com", author: "Alex Hormozi" },
    { id: "p1", type: "profile", name: "Marie Dupont",  domain: "E-commerce & Dropshipping",     profileHref: "#", avatarGradient: "linear-gradient(135deg, #1877F2 0%, #6366F1 100%)", rating: 5 },
    { id: "p2", type: "profile", name: "Jean Konan",    domain: "Marketing Digital & SEO",        profileHref: "#", avatarGradient: "linear-gradient(135deg, #10B981 0%, #0D9488 100%)", rating: 4 },
    { id: "p3", type: "profile", name: "Sophie Martin", domain: "Coaching Business & Mindset",    profileHref: "#", avatarGradient: "linear-gradient(135deg, #F59E0B 0%, #EF4444 100%)", rating: 4 },
  ];

  // ── Notifications ───────────────────────────────────────────────────────────
  const notifications = [
    { id: "n1", type: "actu",       title: "Nouveau : Formation Tunnel de Vente",    body: "La formation Tunnel de Vente de A à Z vient d'être mise à jour avec 3 nouveaux modules.", href: "/formations", date: "2026-03-22" },
    { id: "n2", type: "diagnostic", title: "Ton test hebdo est disponible",           body: "Une nouvelle semaine commence. Passe ton test de progression pour suivre ton évolution.", href: "/espace-membre/diagnostic", date: "2026-03-22" },
    { id: "n3", type: "contenu",    title: "Nouveau contenu publié",                  body: "Israël a publié un nouveau post LinkedIn : '5 erreurs qui tuent ton personal branding'.", href: "/contenus", date: "2026-03-21" },
    { id: "n4", type: "mentee",     title: "Programme Mentee — Nouvelles places",     body: "De nouvelles places se sont ouvertes pour le programme Mentee. Candidature ouverte jusqu'au 31 mars.", href: "/espace-membre/mentee", date: "2026-03-20" },
    { id: "n5", type: "badge",      title: "Badge débloqué : Confirmé",              body: "Ton score de 64/100 t'a permis de débloquer le badge Confirmé. Continue sur ta lancée !", href: "/espace-membre/progression", date: "2026-03-18" },
    { id: "n6", type: "actu",       title: "Ressource gratuite : Guide Personal Branding", body: "Un nouveau guide PDF est disponible en téléchargement gratuit dans la section Ressources.", href: "/ressources", date: "2026-03-16" },
  ];

  const results: Record<string, string> = {};

  // Seed each collection (skip if already has data)
  for (const [colName, data] of [
    ["formations", formations],
    ["ressources", ressources],
    ["outils", outils],
    ["contenus", contenus],
    ["notifications", notifications],
  ] as [string, object[]][]) {
    const col = db.collection(colName);
    const count = await col.countDocuments();
    if (count === 0) {
      await col.insertMany(data.map((d) => ({ ...d })));
      results[colName] = `${data.length} documents insérés`;
    } else {
      results[colName] = `déjà ${count} documents — ignoré`;
    }
  }

  return NextResponse.json({ ok: true, results });
}
